// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hatqilzhkpdlupydlyxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdHFpbHpoa3BkbHVweWRseXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTQ3MTcsImV4cCI6MjA2MzEzMDcxN30.NXMRG9jb448sOMq8r0bnL_RUJ_RP1p7vM4jk1X-RGdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);